export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const GET_TUTORS = 'GET_TUTORS';
export const GET_STUDENTS = 'GET_STUDENTS';
export const EDIT_TUTOR = 'EDIT_TOTUR';
export const EDIT_STUDENT = 'EDIT_STUDENT';
export const EDIT_TUTOR_SUCCESS = 'EDIT_TUTOR_SUCCESS';
export const EDIT_TUTOR_FAIL = 'EDIT_TUTOR_FAIL';
export const EDIT_STUDENT_SUCCESS = 'EDIT_STUDENT_SUCCESS';
export const EDIT_STUDENT_FAIL = 'EDIT_STUDENT_FAIL';
export const DELETE_TUTOR = 'DELETE_TUTOR';
export const DELETE_TUTOR_SUCCESS = 'DELETE_TUTOR_SUCCESS';
export const DELETE_TUTOR_FAIL = 'DELETE_TUTOR_FAIL';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS';
export const DELETE_STUDENT_FAIL = 'DELETE_STUDENT_FAIL';
export const EDIT_ADMIN = 'EDIT_ADMIN';
export const EDIT_ADMIN_SUCCESS = 'EDIT_ADMIN_SUCCESS';
export const EDIT_ADMIN_FAIL = 'EDIT_ADMIN_FAIL';
export const DELETE_ADMIN = 'DELETE_ADMIN';
export const DELETE_ADMIN_SUCCESS = 'DELETE_ADMIN_SUCCESS';
export const DELETE_ADMIN_FAIL = 'DELETE_ADMIN_FAIL';

export const START_LECTURE = 'START_LECTURE';
export const STOP_LECTURE = 'STOP_LECTURE';
export const LOAD_LECTURE = 'LOAD_LECTURE';
export const GET_PUBLISH_TOKEN = 'GET_PUBLISH_TOKEN';
export const GET_PLAY_TOKEN = 'GET_PLAY_TOKEN';

export const GET_MESSAGES = 'GET_MESSAGES';
export const SET_MESSAGES = 'SET_MESSAGES';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const JOIN_CLASSROOM = 'JOIN_CLASSROOM';
export const JOIN_CLASSROOM_SUCCESS = 'JOIN_CLASSROOM_SUCCESS';
export const JOIN_CLASSROOM_FAIL = 'JOIN_CLASSROOM_FAIL';
export const USER_JOINED = 'USER_JOINED';
export const USER_LEFT = 'USER_LEFT';

export const UPLOAD_FILE = 'UPLOAD_FILE';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_FAIL = 'UPLOAD_FILE_FAIL';

export const GET_TUTOR_LECTURES = 'GET_TUTOR_LECTURES';
export const GET_STUDENT_LECTURES = 'GET_STUDENT_LECTURES';
export const GET_TUTOR_CLASSROOMS = 'GET_TUTOR_CLASSROOMS';
export const GET_STUDENT_CLASSROOMS = 'GET_STUDENT_CLASSROOMS';

export const CONNECTION_SUCCESS = 'CONNECTION_SUCCESS';
export const CONNECTION_CLOSE = 'CONNECTION_CLOSE';
export const START_SHARING = 'START_SHARING';
export const START_SHARING_SUCCESS = 'START_SHARING_SUCCESS';
export const START_SHARING_FAIL = 'START_SHARING_FAIL';
export const STOP_SHARING = 'STOP_SHARING';
export const TOGGLE_MIC = 'TOGGLE_MIC';
export const ADD_CLASSROOM = 'ADD_CLASSROOM';
export const GET_CLASSROOMS = 'GET_CLASSROOMS';
export const ADD_LECTURE = 'ADD_LECTURE';
export const GET_LECTURES = 'GET_LECTURES';
export const DELETE_CLASSROOM = 'DELETE_CLASSROOM';
export const DELETE_CLASSROOM_SUCCESS = 'DELETE_CLASSROOM_SUCCESS';
export const DELETE_CLASSROOM_FAIL = 'DELETE_CLASSROOM_FAIL';
export const EDIT_CLASSROOM = 'EDIT_CLASSROOM';
export const EDIT_CLASSROOM_SUCCESS = 'EDIT_CLASSROOM_SUCCESS';
export const EDIT_CLASSROOM_FAIL = 'EDIT_CLASSROOM_FAIL';

export const GET_STUDENTS_OF_CLASSROOM = 'GET_STUDENTS_OF_CLASSROOM';
export const GET_STUDENTS_OF_CLASSROOM_SUCCESS = 'GET_STUDENTS_OF_CLASSROOM_SUCCESS';
export const GET_STUDENTS_OF_CLASSROOM_FAIL = 'GET_STUDENTS_OF_CLASSROOM_FAIL';
export const ADD_STUDENT_TO_CLASSROOM = 'ADD_STUDENT_TO_CLASSROOM';
export const ADD_STUDENT_TO_CLASSROOM_SUCCESS = 'ADD_STUDENT_TO_CLASSROOM_SUCCESS';
export const ADD_STUDENT_TO_CLASSROOM_FAIL = 'ADD_STUDENT_TO_CLASSROOM_FAIL';
export const DELETE_STUDENT_FROM_CLASSROOM = 'DELETE_STUDENT_FROM_CLASSROOM';
export const DELETE_STUDENT_FROM_CLASSROOM_SUCCESS = 'DELETE_STUDENT_FROM_CLASSROOM_SUCCESS';
export const DELETE_STUDENT_FROM_CLASSROOM_FAIL = 'DELETE_STUDENT_FROM_CLASSROOM_FAIL';
// export const BAN_STUDENT = 'BAN_STUDENT';