export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const GET_TUTORS = 'GET_TUTORS';
export const GET_STUDENTS = 'GET_STUDENTS';
export const EDIT_TUTOR = 'EDIT_TOTUR';
export const EDIT_STUDENT = 'EDIT_STUDENT';
export const EDIT_TUTOR_SUCCESS = 'EDIT_TUTOR_SUCCESS';
export const EDIT_TUTOR_FAIL = 'EDIT_TUTOR_FAIL';

export const START_LECTURE = 'START_LECTURE';
export const STOP_LECTURE = 'STOP_LECTURE';

export const GET_MESSAGES = 'GET_MESSAGES';
export const SET_MESSAGES = 'SET_MESSAGES';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const JOIN_CLASSROOM = 'JOIN_CLASSROOM';
export const JOIN_CLASSROOM_SUCCESS = 'JOIN_CLASSROOM_SUCCESS';
export const JOIN_CLASSROOM_FAIL = 'JOIN_CLASSROOM_FAIL';
// export const BAN_STUDENT = 'BAN_STUDENT';
